netcore/WebApplication1/WebApplication1/Models/HotelRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class HotelRoom
    {
        [Key]
        public int HotelRoomId { get; set; }
        [Required]
        [Column(TypeName ="nvarchar(250)")]
        [Display(Name = "Name Room")]
        public string FullName { get; set; }
        public string Images { get; set; }
        public int Amount { get; set; }
        public string Acreage { get; set; }

    }
}

netcore/WebApplication1/WebApplication1/Controllers/HotelRoomsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class HotelRoomsController : Controller
    {
        private IHotelRoomRepository hotelRoomRepository;
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public HotelRoomsController(AppDbContext context, IWebHostEnvironment _webHostEnvironment)
        {
            _context = context;
            webHostEnvironment = _webHostEnvironment;
        }

        // GET: HotelRooms
            public async Task<IActionResult> Index()
            {
                return View(await _context.HotelRooms.ToListAsync());
            }

        // GET: HotelRooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelRoom = await _context.HotelRooms.FindAsync(id);
            HotelRoomsCreateViewModel hotel = new HotelRoomsCreateViewModel();
            hotel.Acreage = hotelRoom.Acreage;
            hotel.Amount = hotelRoom.Amount;
            hotel.FullName = hotelRoom.FullName;
            hotel.urlImages = "/images/" + hotelRoom.Images;
            hotel.Id = hotelRoom.HotelRoomId;
            if (hotelRoom == null)
            {
                return NotFound();
            }

            return View(hotelRoom);
        }

        // GET: HotelRooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HotelRooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("HotelRoomId,FullName,Images,Amount,Acreage")] HotelRoomsCreateViewModel model)
        {
            string nameImages = "";
            if (ModelState.IsValid)
            {
          
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                var fileName = $"{Guid.NewGuid()}_{model.Images.FileName}";
                nameImages = fileName;
                var filePath = Path.Combine(uploadFolder, fileName);
                using (var fs = new FileStream(filePath, FileMode.Create))
                {
                    model.Images.CopyTo(fs);
                }

            }
            var hotel = new HotelRoom()
                {
                    FullName = model.FullName,
                    Amount = model.Amount,
                    Acreage = model.Acreage
                   
                };
            hotel.Images = nameImages;
                _context.HotelRooms.Add(hotel);
                await _context.SaveChangesAsync();
     


            
                return RedirectToAction("Index");
                
   
        }

        // GET: HotelRooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelRoom = await _context.HotelRooms.FindAsync(id);
            HotelRoomsCreateViewModel hotel = new HotelRoomsCreateViewModel();
            hotel.Acreage = hotelRoom.Acreage;
            hotel.Amount = hotelRoom.Amount;
            hotel.FullName = hotelRoom.FullName;
            hotel.urlImages = "/images/"+hotelRoom.Images;
            hotel.Id = hotelRoom.HotelRoomId;

            if (hotelRoom == null)
            {
                return NotFound();
            }
            return View(hotel);
        }

        // POST: HotelRooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id ,[Bind("Id,FullName,Images,Amount,Acreage,urlImages")] HotelRoomsCreateViewModel model)
        {
            string nameImages = "";
            if (ModelState.IsValid)
            {
                if (model.Images != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    var fileName = $"{Guid.NewGuid()}_{model.Images.FileName}";
                    nameImages = fileName;
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using (var fs = new FileStream(filePath, FileMode.Create))
                    {
                        model.Images.CopyTo(fs);
                    }
                }
               

            }
            var hotel = new HotelRoom()
            {
                HotelRoomId = model.Id,
                FullName = model.FullName,
                Amount = model.Amount,
                Acreage = model.Acreage

            };
            if (model.Images != null)
            {
                hotel.Images = nameImages;
            }
            else
            {
                for (int i = 8; i < model.urlImages.Length; i++)
                {
                    hotel.Images += model.urlImages[i];
                }
            }
           
            
            _context.HotelRooms.Update(hotel);
            await _context.SaveChangesAsync();




            return RedirectToAction("Index");
        }

        // GET: HotelRooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelRoom = await _context.HotelRooms
                .FirstOrDefaultAsync(m => m.HotelRoomId == id);
            if (hotelRoom == null)
            {
                return NotFound();
            }

            return View(hotelRoom);
        }

        // POST: HotelRooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hotelRoom = await _context.HotelRooms.FindAsync(id);
            _context.HotelRooms.Remove(hotelRoom);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HotelRoomExists(int id)
        {
            return _context.HotelRooms.Any(e => e.HotelRoomId == id);
        }

        public ViewResult Broom()
        {
            return View();
        }

        public ViewResult Event()
        {
            return View();
        }
        public ViewResult Wedding()
        {
            return View();
        }

        public ViewResult Romantics()
        {
            return View();
        }
    }
}

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Broom.cshtml
@{
    ViewBag.Title = "Hotel room";
}

<div class="container" style="text-align:center; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; ">
    <h1>Rooms</h1>
</div>
<div class="container" style="margin-top:30px">
    <div class="row">
        <div class="col-sm-4" style="text-align:center; color:darkcyan; margin-top:60px">
            <h2>About Me</h2>
            <h5>Photo of me:</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
            <a asp-controller="HotelRooms" asp-action="Index" class="btn btn-warning">BookRoom</a>
        </div>
        <div class="col-sm-8">
            <img src="~/images/bg.jpeg" style="width:100%; height:400px">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <img src="~/images/b2.jpeg" style="width:100%; height:400px">
        </div>
        <div class="col-sm-4" style="text-align:center; color:darkcyan; margin-top:60px">
            <h2>About Me</h2>
            <h5>Photo of me:</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
            <a asp-controller="HotelRooms" asp-action="Index" class="btn btn-warning">BookRoom</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4" style="text-align:center; color:darkcyan; margin-top:60px">
            <h2>About Me</h2>
            <h5>Photo of me:</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
            <a asp-controller="HotelRooms" asp-action="Index" class="btn btn-warning">BookRoom</a>
        </div>
        <div class="col-sm-8">
            <img src="~/images/b3.jpeg" style="width:100%; height:400px">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <img src="~/images/b4.jpeg" style="width:100%; height:400px">
        </div>
        <div class="col-sm-4" style="text-align:center; color:darkcyan; margin-top:60px">
            <h2>About Me</h2>
            <h5>Photo of me:</h5>
            <div class="fakeimg">Fake Image</div>
            <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
            <a asp-controller="HotelRooms" asp-action="Index" class="btn btn-warning">BookRoom</a>
        </div>
    </div>
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Create.cshtml
@model HotelRoomsCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>HotelRoom</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Images" class="control-label"></label>
                <input asp-for="Images" class="form-control" />
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Acreage" class="control-label"></label>
                <input asp-for="Acreage" class="form-control" />
                <span asp-validation-for="Acreage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Delete.cshtml
@model WebApplication1.Models.HotelRoom

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HotelRoom</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Images)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Images)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Acreage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Acreage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HotelRoomId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Details.cshtml
@model WebApplication1.Models.HotelRoom

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="headed mt-3" style="text-align:center">Booking Room Shilla</h1>
<hr />

@*<div>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FullName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FullName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Images)
            </dt>
            <dd class="col-sm-10">
                <img src="~/images/@Url.Content(Model.Images)" style="width:700px; height:500px" />
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Acreage)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Acreage)
            </dd>
        </dl>
    </div>
    <div>
        <a class="btn btn-danger" asp-action="Edit" asp-route-id="@Model.HotelRoomId">Edit</a>
        <a class="btn btn-warning" asp-action="Delete" asp-route-id="@Model.HotelRoomId">Delete</a>
        <a asp-action="Index">Back to List</a>
    </div>*@

<div class=" row justify-content-center">
    <div class="col-sm-6">
        <div class="card my-2">
            <div class="card-header">
                <h3 class="title" style="text-align:center">@Model.FullName</h3>
            </div>
            <div class="card-body text-center">
                <img src="~/images/@Url.Content(Model.Images)" style="width:100%; height:500px" />
                <h3>Amount: $@Model.Amount</h3>
                <h3>Acreage: @Model.Acreage</h3>
                <div class="col" style="text-align:center">
                    <a class="btn btn-danger" asp-action="Edit" asp-route-id="@Model.HotelRoomId">Edit</a>
                    <a class="btn btn-warning" asp-action="Delete" asp-route-id="@Model.HotelRoomId">Delete</a>
                    <a asp-controller="BookRooms" asp-action="Create" class="btn btn-info" style="width:150px"><i class="fa fa-cart-arrow-down"></i>Add To Room</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <a class="btn btn-secondary" asp-action="Index">Back to Room</a>
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Edit.cshtml
@model HotelRoomsCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
 

<h4>HotelRoom</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" class="form-control" />
            <input asp-for="urlImages" type="hidden"/>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row form-group divUpload">
                    <label asp-for="Images" class="control-label custom-file-upload">
                        +
                        
                        <img id="blah" src=@Url.Content(Model.urlImages) alt="your image" />
                    </label>
                    <input asp-for="Images" onchange="readURL(this)" class="form-control" />

                    <label for="file-upload">

                    </label>

                </div>
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Acreage" class="control-label"></label>
                <input asp-for="Acreage" class="form-control" />
                <span asp-validation-for="Acreage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<style>
    input[type="file"] {
        display: none;
    }

    .custom-file-upload {
        width: 160px;
        height: 160px;
        border: 1px solid #ccc;
        display: inline-block;
        padding-top: 37px;
        cursor: pointer;
        font-size: 60px;
        text-align: center;
    }

    #blah {
        display: block;
        margin-top: -129px;
        width:160px;
        height:160px
    }

   

    .divUpload {
        overflow: hidden;
    }
</style>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('blah').src = e.target.result;
                document.getElementById('blah').style.display = 'block';
                document.getElementById('blah').style.width = '160px';
                document.getElementById('blah').style.height = '160px';
            }
            reader.readAsDataURL(input.files[0]);
            document.getElementById('Images').files[0] = input.files[0];
        }
    }
</script>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Event.cshtml
@{
    ViewBag.Title = "Hotel Event";
}

<div class="container-3">
        <div class="cards">
            <h3> Shillamogram</h3>
        </div>
</div>

<div class="container">
    <img src="~/images/event1.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        For the 27th year in a row, Winter Party Festival will take over Miami Beach to help raise money for the LGBTQ community.
        Way back in 1994, Winter Party Festival started out as a one-day mega dance party on Miami Beach, the first ever actually held on the beach. Now, the festival is nearly a full week and has grown into one of the hottest LGBTQ themed parties on the planet.
        It has evolved into an event that celebrates the true spirit of "chosen family" among the global LGBTQ community.
        These days, Winter Party Festival is a massive party with an impressive lineup of internationally acclaimed DJs, which has raised millions of dollars for great causes.
    </p>
    <img src="~/images/event2.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        According to Winter Party Festival organizers The National LGBTQ Taskforce, “For the LGBTQ community and our allies, Winter Party is a place to rejuvenate and recharge. A place to clear our heads, fill our hearts, and engage our minds.
        A place to let loose and kick up our heels. We live in a world that challenges us every day; telling us we’re different, less than, other. And while that may be changing, progress is slow, and inequality persists. It can wear on even the strongest among us.
        It makes us long for safe havens, places where we can be ourselves, surrounded by our chosen family and accepted and loved just the way we are.
        Winter Party is that place, a safe haven where we can LIVE FREE.”
    </p>
    <img src="~/images/event3.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        On Friday, March 6, 2020, the party moves to Wynwood Factory where Hilton Wolman Events presents Heat. DJs J Warren, Joe Pacheco, and Edu Quintas will spin starting at 10 p.m. till 5 a.m. 
        Tickets start at $85 for general admission or $130 for VIP which includes a separate entrance as well as open bar till 2 a.m.
    </p>
    <a href="#" class="btn btn-info">Back To Home</a>
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Index.cshtml
@model IEnumerable<WebApplication1.Models.HotelRoom>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-3">
     <div class="cards">
       <h3> Shillamogram Rooms</h3>
      </div>
</div>
<div class="row">
    @foreach (var hotel in Model)
    {
        var avatarPath = $"/images/{(hotel.Images ?? "noavatar.png")} ";
        <div class="col-sm-3">
            <div class="card my-2">
                <div class="card-header">
                    <h4>@hotel.FullName</h4>
                </div>
                <img src="@avatarPath" class="card-img-top" />
                <div class="card-footer">
                    @*<a href="Home/Details/1">View</a>
                        @Html.ActionLink("View","Details","Home", new { id = emp.Id })*@
                    <a asp-controller="HotelRooms" asp-action="Details" asp-route-id="@hotel.HotelRoomId" class="btn btn-warning">View</a>
                    <a asp-controller="HotelRooms" asp-action="Edit" asp-route-id="@hotel.HotelRoomId" class="btn btn-primary">Edit</a>
                    <a asp-controller="HotelRooms" asp-action="Details" asp-route-id="@hotel.HotelRoomId" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    }
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Romantics.cshtml
@{
    ViewBag.Title = "Hotel All Romantics";
}

<div class="container-3">
    <div class="cards">
         <h3> Shillamogram</h3>
     </div>
</div>
<div class="container">
    <img src="~/images/view1.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        Shilla is a beautiful rooftop cafe rooftop, with an overhead view overlooking Vincom Ba Trieu,
        the view reaches the intersection of Ho Tung Mau, a cool and quiet Church view for young people to check in.
        Not only a cafe serving drinks such as Tea, Coffee, Juice, Yogurt, but also eye-catching detox drinks, the taste is also great!
    </p>
    <img src="~/images/view2.jpg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        From the swimming pool, you can freely relax, enjoy a panoramic view of the beautiful city. Marina Bay Sand also offers a system of modern, comfortable rooms with elegant, luxurious and eye-catching design.
        This is one of the ideal resorts in Singapore that you should choose.
    </p>
    <img src="~/images/view3.jpg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        An outdoor swimming pool system on the 16th floor, equipped with a mini bar, and diverse culinary services. Although it is a luxury hotel, it has a quite affordable price, suitable for all types of tourists. However, you should contact to book a room in advance to get the best accommodation and the most reasonable price.
    </p>
</div>

netcore/WebApplication1/WebApplication1/Views/HotelRooms/Wedding.cshtml
@{
    ViewBag.Title = "Hotel Wedding";
}

<div class="container-3">
    <div class="cards">
       <h3>Shillamogram</h3>
    </div>
</div>
<div class="container">
    <img src="~/images/wedding1.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        Starting as an event organization company with many years of experience in the field of weddings,
        Dora Wedding & Events always provides customers smart, economical and convenient service packages,
        a solution for all. The bride and groom prepare for their big day. Besides, Dora Wedding & Events is increasingly expanding and developing diversely in all different events such as birthdays, anniversaries, opening parties ... still following the criteria of returning the best services for for customers.
    </p>
    <img src="~/images/wedding2.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">
        Dora Wedding & Events, with the strength of experience of a team full of competence, professional style, serious working spirit.
        Young human resources have constant creativity and multi-styled artistic taste. An in-depth investment in a creative staff as well as a system of professional equipment. We give customers not only job satisfaction but also trust and long-term cooperation.
        Class and difference only at Dora Wedding & Events you will have a dream wedding, bring your own style because you deserve it.
    </p>
    <img src="~/images/wedding3.jpeg" style="width:100%" />
    <p class="texts mt-2 mb-2">

        We do not pursue the epitome of a leading event organizer, we focus on producing ideas and services that the top event planners don't have. We are proud to be accompanied by growth and to record memorable marks in your success.
    </p>
    <a href="#" class="btn btn-info">Back To Home</a>
</div>